# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-23 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
