# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-11 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncuba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('categories', models.ManyToManyField(to='oncuba.Categoria')),
                ('proyectos', models.ManyToManyField(to='oncuba.Proyecto')),
            ],
            options={
                'verbose_name_plural': 'roles',
            },
        ),
    ]
