# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-12 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oncuba', '0003_auto_20161012_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressEntidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_one', models.CharField(max_length=200, verbose_name='Direcci\xf3n')),
                ('provincia', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, default=' ', max_length=100, verbose_name='Descripci\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='AddressPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_one', models.CharField(max_length=200, verbose_name='Direcci\xf3n')),
                ('provincia', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, default=' ', max_length=100, verbose_name='Descripci\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='EmailEntidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electr\xf3nico')),
                ('descripcion', models.CharField(blank=True, default=' ', max_length=100, verbose_name='Descripci\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='EmailPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electr\xf3nico')),
                ('descripcion', models.CharField(blank=True, default=' ', max_length=100, verbose_name='Descripci\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=' ', max_length=100, verbose_name='Nombre')),
                ('servicios', models.CharField(max_length=100, verbose_name='Servicios/Productos')),
                ('persona', models.CharField(max_length=200, verbose_name='Nombre de Persona de Contacto')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo de Persona de Contacto')),
                ('pais', models.CharField(default='Cuba', max_length=50, verbose_name='Pa\xeds')),
                ('aniversario', models.DateField()),
                ('fiesta', models.DateField(verbose_name='Fiesta Nacional')),
                ('sitio_web', models.URLField(verbose_name='Sitio Web')),
                ('observaciones', models.TextField(blank=True)),
                ('categoria', models.ManyToManyField(to='oncuba.Categoria')),
                ('proyecto', models.ManyToManyField(to='oncuba.Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumberEntidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='N\xfamero de Tel\xe9fono')),
                ('descripcion', models.CharField(blank=True, default=' ', max_length=100, verbose_name='Descripci\xf3n')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncuba.Entidad')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumberPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='N\xfamero de Tel\xe9fono')),
                ('descripcion', models.CharField(blank=True, default=' ', max_length=100, verbose_name='Descripci\xf3n')),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='email',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='contact',
        ),
        migrations.AddField(
            model_name='persona',
            name='apellidos',
            field=models.CharField(default=' ', max_length=100, verbose_name='Apellido(s)'),
        ),
        migrations.AddField(
            model_name='persona',
            name='categoria',
            field=models.ManyToManyField(to='oncuba.Categoria'),
        ),
        migrations.AddField(
            model_name='persona',
            name='nombre',
            field=models.CharField(default=' ', max_length=100, verbose_name='Nombre(s)'),
        ),
        migrations.AddField(
            model_name='persona',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='pais',
            field=models.CharField(default='Cuba', max_length=50, verbose_name='Pa\xeds'),
        ),
        migrations.AddField(
            model_name='persona',
            name='proyecto',
            field=models.ManyToManyField(to='oncuba.Proyecto'),
        ),
        migrations.AddField(
            model_name='persona',
            name='sitio_web',
            field=models.URLField(blank=True, verbose_name='Sitio Web'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
        migrations.AddField(
            model_name='phonenumberperson',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncuba.Persona'),
        ),
        migrations.AddField(
            model_name='emailperson',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncuba.Persona'),
        ),
        migrations.AddField(
            model_name='emailentidad',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncuba.Entidad'),
        ),
        migrations.AddField(
            model_name='addressperson',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncuba.Persona'),
        ),
        migrations.AddField(
            model_name='addressentidad',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncuba.Entidad'),
        ),
    ]
