# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-12 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncuba', '0004_auto_20161012_0048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entidad',
            options={'verbose_name_plural': 'entidades'},
        ),
        migrations.AlterField(
            model_name='entidad',
            name='aniversario',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='fiesta',
            field=models.DateField(blank=True, verbose_name='Fiesta Nacional'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='sitio_web',
            field=models.URLField(blank=True, verbose_name='Sitio Web'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('S', 'Solter'), ('C', 'Casad'), ('V', 'Viud'), ('D', 'Divorciad')], max_length=1),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_de_nacimiento',
            field=models.DateField(blank=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1),
        ),
    ]
