# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-12 01:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oncuba', '0005_auto_20161012_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnCubaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=200)),
                ('proyecto', models.ManyToManyField(to='oncuba.Proyecto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='addressentidad',
            options={'verbose_name': 'Direcci\xf3n', 'verbose_name_plural': 'Direcciones Disponibles'},
        ),
        migrations.AlterModelOptions(
            name='addressperson',
            options={'verbose_name': 'Direcci\xf3n', 'verbose_name_plural': 'Direcciones Disponibles'},
        ),
        migrations.AlterModelOptions(
            name='emailentidad',
            options={'verbose_name': 'Correo Electr\xf3nico', 'verbose_name_plural': 'Listado de Correos'},
        ),
        migrations.AlterModelOptions(
            name='emailperson',
            options={'verbose_name': 'Correo Electr\xf3nico', 'verbose_name_plural': 'Listado de Correos'},
        ),
        migrations.AlterModelOptions(
            name='phonenumberentidad',
            options={'verbose_name': 'N\xfamero de Tel\xe9fono', 'verbose_name_plural': 'N\xfameros de Tel\xe9fono'},
        ),
        migrations.AlterModelOptions(
            name='phonenumberperson',
            options={'verbose_name': 'N\xfamero de Tel\xe9fono', 'verbose_name_plural': 'N\xfameros de Tel\xe9fono'},
        ),
    ]
