# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-12 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oncuba', '0006_auto_20161012_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oncuba.OnCubaUser', verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='persona',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oncuba.OnCubaUser', verbose_name='Creado por'),
        ),
    ]
