# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-14 02:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('oncuba', '0008_auto_20161012_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='date_marked',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 10, 14, 2, 4, 58, 321710, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='entidad',
            name='marked_for_deletion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persona',
            name='date_marked',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 10, 14, 2, 4, 58, 312339, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='persona',
            name='marked_for_deletion',
            field=models.BooleanField(default=False),
        ),
    ]
