# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-14 03:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('oncuba', '0009_auto_20161014_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='oncubauser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncuba.Role'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='date_marked',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 10, 14, 3, 47, 33, 253890, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='persona',
            name='date_marked',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 10, 14, 3, 47, 33, 245356, tzinfo=utc)),
        ),
    ]
