# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-14 23:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oncuba', '0010_auto_20161014_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('C', 'Creado'), ('M', 'Modificado'), ('B', 'Borrado'), ('I', 'Invitado')], max_length=2)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='entidad',
            name='date_marked',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='persona',
            name='date_marked',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
