# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-17 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncuba', '0012_auto_20161017_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=' ', max_length=100, verbose_name='Nombre(s)')),
                ('apellidos', models.CharField(default=' ', max_length=100, verbose_name='Apellido(s)')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electr\xf3nico')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('cargo', models.CharField(max_length=200)),
                ('proyectos', models.ManyToManyField(to='oncuba.Proyecto')),
            ],
        ),
    ]
