# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-17 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oncuba', '0013_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Staff'},
        ),
        migrations.AlterModelOptions(
            name='usertracker',
            options={'verbose_name': 'Historial', 'verbose_name_plural': 'Historial'},
        ),
        migrations.AddField(
            model_name='usertracker',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncuba.OnCubaUser'),
        ),
        migrations.AddField(
            model_name='usertracker',
            name='entidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncuba.Entidad'),
        ),
        migrations.AddField(
            model_name='usertracker',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oncuba.Persona'),
        ),
    ]
