# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-20 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncuba', '0017_auto_20161019_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacion',
            name='usada',
            field=models.BooleanField(default=False),
        ),
    ]
