# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-10 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oncuba', '0019_auto_20161025_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(max_length=200, verbose_name='Persona de Contacto')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('numbers', models.CharField(blank=True, max_length=100, null=True, verbose_name='N\xfamero(s) de Tel\xe9fono')),
                ('emails', models.CharField(blank=True, max_length=100, null=True, verbose_name='Correo(s) Electr\xf3nico(s)')),
            ],
            options={
                'verbose_name': 'Persona de Contacto',
                'verbose_name_plural': 'Personas de Contacto',
            },
        ),
        migrations.RemoveField(
            model_name='entidad',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='entidad',
            name='persona',
        ),
        migrations.AlterField(
            model_name='entidad',
            name='nacionalidad',
            field=models.CharField(default='Cubana', max_length=50, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nacionalidad',
            field=models.CharField(default='Cubana', max_length=50, verbose_name='nacionalidad'),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oncuba.Entidad'),
        ),
    ]
