# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-11 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncuba', '0022_auto_20161111_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='aniversario',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='fiesta',
            field=models.DateField(blank=True, null=True, verbose_name='Fiesta Nacional'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_de_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
