# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-19 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncuba', '0024_auto_20161121_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='lugar_de_trabajo',
            field=models.CharField(max_length=100, verbose_name='Lugar de Trabajo'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ocupacion',
            field=models.CharField(max_length=100, verbose_name='Ocupaci\xf3n'),
        ),
    ]
